# Generated by Django 6.0.7 on 2026-07-08 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorDefinition',
            fields=[
                ('error_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details_newbie', models.TextField()),
                ('details_comfortable', models.TextField()),
                ('details_facts', models.TextField()),
                ('broken', models.TextField(blank=True, null=True)),
                ('fixed', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticePuzzle',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('error_name', models.CharField(max_length=200)),
                ('broken', models.TextField()),
                ('hint', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('errors', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=100)),
                ('status', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('issues', models.JSONField(default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
